adx_contentdisposition: 756150000
adx_enabletracking: false
adx_excludefromsearch: false
adx_hiddenfromsitemap: false
adx_name: Product image 1.png
adx_parentpageid: 6ecf634b-837e-4b73-910d-5f1ef6eafbe7
adx_partialurl: Product image 1.png
adx_publishingstateid: c064f79d-1458-42f5-a020-6292edb17039
adx_webfileid: 55e2bb94-93b6-441f-9f06-49de3bb90dd8
annotationid: c9719dbc-18e2-ee11-904c-6045bd721622
filename: Product image 1.png
isdocument: true
mimetype: image/png
objectid: 55e2bb94-93b6-441f-9f06-49de3bb90dd8
objecttypecode: adx_webfile
